<?php

namespace App\Models;

/**
 * Eloquent class to describe the Invoice table.
 *
 * automatically generated by ModelGenerator.php
 */
class Invoice extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'Invoice';

    public $primaryKey = 'Id';

    public $timestamps = false;
	protected $casts = [
        'Id' => 'integer',
		'totalDiscountAmount' => 'decimal:2',
		'totalSalesAmount' => 'decimal:2',
		'netAmount' => 'decimal:2',
		'totalAmount' => 'decimal:2',
		'extraDiscountAmount' => 'decimal:2',
		'totalItemsDiscountAmount' => 'decimal:2',
    ];

    protected $fillable = ['issuer_id', 'receiver_id', 'documentType', 'documentTypeVersion', 'dateTimeIssued', 'taxpayerActivityCode',
        'internalID', 'purchaseOrderReference', 'purchaseOrderDescription', 'salesOrderReference', 'salesOrderDescription',
        'proformaInvoiceNumber', 'totalDiscountAmount', 'totalSalesAmount', 'netAmount', 'totalAmount', 'extraDiscountAmount',
        'totalItemsDiscountAmount'];

    public function getDates()
    {
        return ['dateTimeIssued'];
    }

    public function delivery()
    {
        return $this->belongsTo('App\Models\Delivery', 'delivery_id', 'Id');
    }

    public function issuer()
    {
        return $this->belongsTo('App\Models\Issuer', 'issuer_id', 'Id');
    }

    public function payment()
    {
        return $this->belongsTo('App\Models\Payment', 'payment_id', 'Id');
    }

    public function receiver()
    {
        return $this->belongsTo('App\Models\Receiver', 'receiver_id', 'Id');
    }

    public function invoiceLines()
    {
        return $this->hasMany('App\Models\InvoiceLine', 'invoice_id', 'Id');
    }

    public function taxTotals()
    {
        return $this->hasMany('App\Models\TaxTotal', 'invoice_id', 'Id');
    }
}
