<?php

namespace App\Models;

//use App\Models\Item;

/**
 * Eloquent class to describe the InvoiceLine table.
 *
 * automatically generated by ModelGenerator.php
 */
class InvoiceLine extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'InvoiceLine';

    public $primaryKey = 'Id';
	//protected $appends = ['item'];

    protected $fillable = ['description', 'itemType', 'itemCode', 'unitType', 'quantity', 'internalCode', 'salesTotal',
        'total', 'valueDifference', 'totalTaxableFees', 'netTotal', 'itemsDiscount', 'invoice_id' ];

    public function discount()
    {
        return $this->belongsTo('App\Models\Discount', 'discount_id', 'Id');
    }

    //public function getItemAttribute()
    public function item()
    {
		//return Item::firstWhere('itemCode', $this->itemCode);
		return $this->belongsTo('App\Models\ETAItem', 'itemCode', 'itemCode');
    }

    public function invoice()
    {
        return $this->belongsTo('App\Models\Invoice', 'invoice_id', 'Id');
    }

    public function unitValue()
    {
        return $this->belongsTo('App\Models\Value', 'unitValue_id', 'Id');
    }

    public function taxableItems()
    {
        return $this->hasMany('App\Models\TaxableItem', 'invoiceline_id', 'Id');
    }
}
