<?php

namespace App\Models;

/**
 * Eloquent class to describe the TaxableItem table.
 *
 * automatically generated by ModelGenerator.php
 */
class ReceiptTaxableItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'rc_taxableItem';

    public $primaryKey = 'Id';
    protected $casts = [
        'Id'      => 'integer',
        'amount'  => 'decimal:5', 
        'rate'    => 'decimal:5', 
    ];

    protected $fillable = ['taxType', 'amount', 'subType', 'rate'];

    public function receiptItem()
    {
        return $this->belongsTo('App\Models\ReceiptItem', 'receiptItem_id', 'Id');
    }
}
